on: push
name: Publish Dokka
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Generate Dokka
      run: ./gradlew dokkaHtml

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=build/dokka/html
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
